### ISSUE TITLE
API is a little bit unclear

### ISSUE THREAD

**Issue by Danappelxx** [czechboy0/Environment#3]
Since every call creates a new instance of `Environment`, it makes it seem like a new environment is being created each time. I don't know if you have plans for this, but it makes more sense to me for the functions to be static.

`Evironment().getVar` -> `Environment.getVar`

**Comment by czechboy0** [comment]
I've considered this, and it's probably the most pragmatic thing to do. I first built it as a struct so that it could technically be replaced by a testing version in tests, but as there's no protocol `Environment` yet, it doesn't bring us anything.

I'd accept a PR if you have time. 👍
